# Site settings
title: Pale Kai
subtitle: Outrigger Canoe Club
email: palekaioutrigger@gmail.com
description: A competitive Hawaiian style outrigger canoe racing for men and women right here on the beautiful central coast waters of California.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.palekai.org" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: United States of America
phone: 
permalink: /:categories/:year/:title/

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 1

tiles-source-news: posts
tiles-count-news: 2

# Pagination
paginate: 5
paginate_path: "blog/page/:num/"

# Social settings
500px_url:
facebook_url: https://www.facebook.com/PaleKaiOutrigger
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/palekaioutrigger/
linkedin_url: 
pinterest_url:
slack_url:
youtube_url: https://www.youtube.com/channel/UCDo7B_WRAVOs2htZyMkJT4A/playlists

# Build settings
markdown: kramdown

sass:
  style: compressed
  sass_dir: _sass

gems:
  - jekyll-redirect-from
  - jekyll-paginate

include:
  - /_pages

collections:
  products:
    output: true

